In [9]:
import numpy as np
import requests
import alpaca_trade_api as tradeapi

APCA_API_KEY_ID="PK6JEVO7YQV3FB39N1FG"
APCA_API_SECRET_KEY="Z8Y5DStoQiadfU7GkODmMEvWg7fiDmAVSVyqKWZ6"
APCA_API_BASE_URL="https://paper-api.alpaca.markets"
ALPACA_API_DATA_URL = "wss://data.alpaca.markets"

In [3]:
api = tradeapi.REST("PK6JEVO7YQV3FB39N1FG", "Z8Y5DStoQiadfU7GkODmMEvWg7fiDmAVSVyqKWZ6", "https://paper-api.alpaca.markets",\
                   api_version='v2')

#Getting account info
account = api.get_account()
print(api.get_quotes("AAPL", "2021-02-08", "2021-02-08", limit=10).df)

                                 ask_exchange  ask_price  ask_size  \
timestamp
2021-02-08 09:00:00.038100+00:00            T     177.00         5
2021-02-08 09:00:00.109400+00:00            T     177.00         6
2021-02-08 09:00:00.129100+00:00            P     137.90         1
2021-02-08 09:00:00.129100+00:00            P     139.49         2
2021-02-08 09:00:00.129100+00:00            P     137.90         1
2021-02-08 09:00:00.129100+00:00            P     137.90         1
2021-02-08 09:00:00.129100+00:00            P     137.90         1
2021-02-08 09:00:00.129100+00:00            P     137.90         1
2021-02-08 09:00:00.129100+00:00            P     137.90         1
2021-02-08 09:00:00.129100+00:00            P     137.90         1

                                 bid_exchange  bid_price  bid_size conditions
timestamp
2021-02-08 09:00:00.038100+00:00            T       0.00         0        [?]
2021-02-08 09:00:00.109400+00:00            T       0.00         0        [?]
2021-02-08 09:00:00.129100+00:00            P     131.21         1        [?]
2021-02-08 09:00:00.129100+00:00            T       0.00         0        [?]
2021-02-08 09:00:00.129100+00:00            P     125.00         1        [?]
2021-02-08 09:00:00.129100+00:00            P     121.99         1        [?]
2021-02-08 09:00:00.129100+00:00            P     128.38         1        [?]
2021-02-08 09:00:00.129100+00:00            P     126.50         1        [?]
2021-02-08 09:00:00.129100+00:00            P     126.00         1        [?]
2021-02-08 09:00:00.129100+00:00            P     130.00         1        [?]

In [4]:
apple = api.get_barset('AAPL', 'day', limit=1000)

In [5]:
apple.df.head()

                             AAPL
                             open    high     low   close    volume
time
2017-06-05 00:00:00-04:00  154.34  154.45  153.46  153.93  20349569
2017-06-06 00:00:00-04:00  153.90  155.81  153.78  154.45  21408385
2017-06-07 00:00:00-04:00  155.01  155.98  154.48  155.37  17394656
2017-06-08 00:00:00-04:00  155.25  155.54  154.40  154.92  15637031
2017-06-09 00:00:00-04:00  155.19  155.19  146.02  148.97  55236738

In [7]:
from time import sleep
import logging

In [8]:
logging.basicConfig(filename='error.log',\
                   level=logging.WARNING,\
                   format='%(asctime)s:%(velelname)s:%(message)s')

In [ ]:
#create websocket
conn = tradeapi.stream2.StreamConn(APCA_API_KEY_ID,\
                                  APCA_API_SECRET_KEY,\
                                  data_url = APCA_API_BASE_URL,\
                                  data_url=ALPACA_API_DATA_URL,\
                                  data_stream='alpacadatav1')

In [20]:
def time_till_market_close():
    clock = api.get_clock()
    return (clock.next_close - clock.timestamp)

def wait_for_market_open():
    clock = api.get_clock()
    if clock.is_open == False:
        #sleep unt
        time.sleep(time_till_market_close.total_seconds())

In [21]:
time_till_market_close()

Timedelta('0 days 00:46:08.146355620')

In [19]:
time.sleep(5)

In [33]:
api.submit_order(symbol='TD', qty=100, side='buy', type='market',\
                time_in_force='day')

Order({   'asset_class': 'us_equity',
    'asset_id': '94feb9d0-bacc-4b3a-9fa7-d372b473c10f',
    'canceled_at': None,
    'client_order_id': '2a3c827b-6799-48d6-ba96-2c3c9a6006db',
    'created_at': '2021-05-24T19:30:51.157605Z',
    'expired_at': None,
    'extended_hours': False,
    'failed_at': None,
    'filled_at': None,
    'filled_avg_price': None,
    'filled_qty': '0',
    'hwm': None,
    'id': '97a6fab8-75d8-4010-8d5c-fd5aed3e275f',
    'legs': None,
    'limit_price': None,
    'notional': None,
    'order_class': '',
    'order_type': 'market',
    'qty': '100',
    'replaced_at': None,
    'replaced_by': None,
    'replaces': None,
    'side': 'buy',
    'status': 'accepted',
    'stop_price': None,
    'submitted_at': '2021-05-24T19:30:51.148798Z',
    'symbol': 'TD',
    'time_in_force': 'day',
    'trail_percent': None,
    'trail_price': None,
    'type': 'market',
    'updated_at': '2021-05-24T19:30:51.157605Z'})

In [24]:
@conn.on(r'^trade_updates$')
async def on_trade_updates(conn, channel, trade):
    if trade.order['order_type'] != 'market' and trade.order['filled_qty'] == '100':
        # trade closed - look for new trade
        trade_params = set_trade_params(candlesticks.df.AAPL)

NameError: name 'conn' is not defined

In [26]:
api.list_positions()

[Position({   'asset_class': 'us_equity',
     'asset_id': '03fb07bb-5db1-4077-8dea-5d711b272625',
     'avg_entry_price': '77.73',
     'change_today': '0.0069975379033303',
     'cost_basis': '777.3',
     'current_price': '77.71',
     'exchange': 'NASDAQ',
     'lastday_price': '77.17',
     'market_value': '777.1',
     'qty': '10',
     'side': 'long',
     'symbol': 'AMD',
     'unrealized_intraday_pl': '-0.2',
     'unrealized_intraday_plpc': '-0.0002573009134182',
     'unrealized_pl': '-0.2',
     'unrealized_plpc': '-0.0002573009134182'})]

------------------------------------------------------------------
<u><h2>Alpha Vantage Testing</h2></u>

In [37]:
alphavantage_api_key = 'B78KWAB6MWH7YLTV'

In [56]:
from alpha_vantage.timeseries import TimeSeries
from alpha_vantage.techindicators import TechIndicators
from alpha_vantage.sectorperformance import SectorPerformances

app = TimeSeries(alphavantage_api_key, output_format='pandas')
ind = TechIndicators(alphavantage_api_key, output_format = 'pandas')

In [47]:
help(app)

Help on TimeSeries in module alpha_vantage.timeseries object:

class TimeSeries(alpha_vantage.alphavantage.AlphaVantage)
 |  TimeSeries(key=None, output_format='json', treat_info_as_error=True, indexing_type='date', proxy=None, rapidapi=False)
 |
 |  This class implements all the api calls to times series
 |
 |  Method resolution order:
 |      TimeSeries
 |      alpha_vantage.alphavantage.AlphaVantage
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  get_daily(self, symbol, outputsize='compact')
 |      Return daily time series in two json objects as data and
 |      meta_data. It raises ValueError when problems arise
 |
 |      Keyword Arguments:
 |          symbol:  the symbol for the equity we want to get its data
 |          outputsize:  The size of the call, supported values are
 |              'compact' and 'full; the first returns the last 100 points in the
 |              data series, and 'full' returns the full-length daily times
 |              series, commonly above 1MB (default 'compact')
 |
 |  get_daily_adjusted(self, symbol, outputsize='compact')
 |      Return daily adjusted (date, daily open, daily high, daily low,
 |      daily close, daily split/dividend-adjusted close, daily volume)
 |      time series in two json objects as data and
 |      meta_data. It raises ValueError when problems arise
 |
 |      Keyword Arguments:
 |          symbol:  the symbol for the equity we want to get its data
 |          outputsize:  The size of the call, supported values are
 |              'compact' and 'full; the first returns the last 100 points in the
 |              data series, and 'full' returns the full-length daily times
 |              series, commonly above 1MB (default 'compact')
 |
 |  get_intraday(self, symbol, interval='15min', outputsize='compact')
 |      Return intraday time series in two json objects as data and
 |      meta_data. It raises ValueError when problems arise
 |
 |      Keyword Arguments:
 |          symbol:  the symbol for the equity we want to get its data
 |          interval:  time interval between two conscutive values,
 |              supported values are '1min', '5min', '15min', '30min', '60min'
 |              (default '15min')
 |          outputsize:  The size of the call, supported values are
 |              'compact' and 'full; the first returns the last 100 points in the
 |              data series, and 'full' returns the full-length intraday times
 |              series, commonly above 1MB (default 'compact')
 |
 |  get_intraday_extended(self, symbol, interval='15min', slice='year1month1')
 |      Return extended intraday time series in one csv_reader object.
 |      It raises ValueError when problems arise
 |
 |      Keyword Arguments:
 |          symbol:  the symbol for the equity we want to get its data
 |          interval:  time interval between two conscutive values,
 |              supported values are '1min', '5min', '15min', '30min', '60min'
 |              (default '15min')
 |          slice: the trailing 2 years of intraday data is evenly divided into
 |              24 "slices" - year1month1, year1month2, ..., year2month12
 |
 |  get_monthly(self, symbol)
 |      Return monthly time series in two json objects as data and
 |      meta_data. It raises ValueError when problems arise
 |
 |      Keyword Arguments:
 |          symbol:  the symbol for the equity we want to get its data
 |
 |  get_monthly_adjusted(self, symbol)
 |      Return monthly time series in two json objects as data and
 |      meta_data. It raises ValueError when problems arise
 |
 |      Keyword Arguments:
 |          symbol:  the symbol for the equity we want to get its data
 |
 |  get_quote_endpoint(self, symbol)
 |      Return the latest price and volume information for a
 |       security of your choice
 |
 |      Keyword Arguments:
 |          symbol:  the symbol for the equity we want to get its data
 |
 |  get_symbol_search(self, keywords)
 |      Return best matching symbols and market information
 |      based on keywords. It raises ValueError when problems arise
 |
 |      Keyword Arguments:
 |          keywords: the keywords to query on
 |
 |  get_weekly(self, symbol)
 |      Return weekly time series in two json objects as data and
 |      meta_data. It raises ValueError when problems arise
 |
 |      Keyword Arguments:
 |          symbol:  the symbol for the equity we want to get its data
 |
 |  get_weekly_adjusted(self, symbol)
 |      weekly adjusted time series (last trading day of each week,
 |      weekly open, weekly high, weekly low, weekly close, weekly adjusted
 |      close, weekly volume, weekly dividend) of the equity specified,
 |      covering up to 20 years of historical data.
 |      Keyword Arguments:
 |          symbol:  the symbol for the equity we want to get its data
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from alpha_vantage.alphavantage.AlphaVantage:
 |
 |  __init__(self, key=None, output_format='json', treat_info_as_error=True, indexing_type='date', proxy=None, rapidapi=False)
 |      Initialize the class
 |
 |      Keyword Arguments:
 |          key:  Alpha Vantage api key
 |          retries:  Maximum amount of retries in case of faulty connection or
 |              server not able to answer the call.
 |          treat_info_as_error: Treat information from the api as errors
 |          output_format:  Either 'json', 'pandas' os 'csv'
 |          indexing_type: Either 'date' to use the default date string given
 |          by the alpha vantage api call or 'integer' if you just want an
 |          integer indexing on your dataframe. Only valid, when the
 |          output_format is 'pandas'
 |          proxy: Dictionary mapping protocol or protocol and hostname to
 |          the URL of the proxy.
 |          rapidapi: Boolean describing whether or not the API key is
 |          through the RapidAPI platform or not
 |
 |  map_to_matype(self, matype)
 |      Convert to the alpha vantage math type integer. It returns an
 |      integer correspondent to the type of math to apply to a function. It
 |      raises ValueError if an integer greater than the supported math types
 |      is given.
 |
 |      Keyword Arguments:
 |          matype:  The math type of the alpha vantage api. It accepts
 |          integers or a string representing the math type.
 |
 |              * 0 = Simple Moving Average (SMA),
 |              * 1 = Exponential Moving Average (EMA),
 |              * 2 = Weighted Moving Average (WMA),
 |              * 3 = Double Exponential Moving Average (DEMA),
 |              * 4 = Triple Exponential Moving Average (TEMA),
 |              * 5 = Triangular Moving Average (TRIMA),
 |              * 6 = T3 Moving Average,
 |              * 7 = Kaufman Adaptive Moving Average (KAMA),
 |              * 8 = MESA Adaptive Moving Average (MAMA)
 |
 |  set_proxy(self, proxy=None)
 |      Set a new proxy configuration
 |
 |      Keyword Arguments:
 |          proxy: Dictionary mapping protocol or protocol and hostname to
 |          the URL of the proxy.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from alpha_vantage.alphavantage.AlphaVantage:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)

In [51]:
apple_stock = app.get_daily_adjusted('AAPL', outputsize='full')

In [55]:
apple_stock[0].head()

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient
date,,,,,,,,
2021-05-24,126.01,127.940,125.94,127.10,127.10,62917187.0,0.0,1.0
2021-05-21,127.82,128.000,125.21,125.43,125.43,79295436.0,0.0,1.0
2021-05-20,125.23,127.720,125.10,127.31,127.31,76857123.0,0.0,1.0
2021-05-19,123.16,124.915,122.86,124.69,124.69,92611989.0,0.0,1.0
2021-05-18,126.56,126.990,124.78,124.85,124.85,63342929.0,0.0,1.0

In [59]:
help(ind.get_tema)

Help on method get_tema in module alpha_vantage.techindicators:

get_tema(symbol, interval='daily', time_period=20, series_type='close') method of alpha_vantage.techindicators.TechIndicators instance
    Return triple exponential moving average time series in two json
    objects as data and meta_data. It raises ValueError when problems arise

    Keyword Arguments:
        symbol:  the symbol for the equity we want to get its data
        interval:  time interval between two conscutive values,
            supported values are '1min', '5min', '15min', '30min', '60min', 'daily',
            'weekly', 'monthly' (default 'daily')
        time_period:  How many data points to average (default 20)
        series_type:  The desired price type in the time series. Four types
            are supported: 'close', 'open', 'high', 'low' (default 'close')

In [64]:
ind.get_tema("AAPL")[0].head(20)

              TEMA
date
2000-01-24  0.8170
2000-01-25  0.8319
2000-01-26  0.8397
2000-01-27  0.8454
2000-01-28  0.8330
2000-01-31  0.8269
2000-02-01  0.8146
2000-02-02  0.8015
2000-02-03  0.7997
2000-02-04  0.8074
2000-02-07  0.8258
2000-02-08  0.8423
2000-02-09  0.8511
2000-02-10  0.8598
2000-02-11  0.8572
2000-02-14  0.8688
2000-02-15  0.8844
2000-02-16  0.8870
2000-02-17  0.8903
2000-02-18  0.8854

In [63]:
apple_stock[0].head()

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient
date,,,,,,,,
2021-05-24,126.01,127.940,125.94,127.10,127.10,62917187.0,0.0,1.0
2021-05-21,127.82,128.000,125.21,125.43,125.43,79295436.0,0.0,1.0
2021-05-20,125.23,127.720,125.10,127.31,127.31,76857123.0,0.0,1.0
2021-05-19,123.16,124.915,122.86,124.69,124.69,92611989.0,0.0,1.0
2021-05-18,126.56,126.990,124.78,124.85,124.85,63342929.0,0.0,1.0

---------------------------------------------------------------------------------------------------------------
<u><h2>Backtrader</h2></u>

In [65]:
import backtrader

ModuleNotFoundError: No module named 'backtrader'

In [67]:
from __future__ import (absolute_import, division, print_function,unicode_literals)